linters:
  flake8:
    fixer: false
    ignore: I002
fixers:
  enable: false
review:
  fail_on_comments: false
files:
    # Ignore the files that match these glob patterns.
    # Be careful to quote strings as `*` has special
    # meaning in YAML files.
    ignore:
        - 'docs/**/*'
        - 'monet/data/*'
