name: monet_docs

channels:
    - conda-forge
    - defaults

dependencies:
    - python==3.7
    - sphinx_rtd_theme==0.1.9
    - numpy
    - pandas
    - xarray
    - dask
    - cartopy
    - matplotlib-base
    - seaborn
    - python-stratify
    - pydecorate
    - xesmf
